config/routes.rb
Escshop::Application.routes.draw do
 
  resources :orders

  resources :products do
    resource :basket
  end

  root to: "products#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address_1, :address_2, :city, :email, :name, :postcode, :stripe_card_token, :stripe_customer_token

  has_many :order_products
  has_many :products, through: :order_products

  validates :name, presence: true
  validates :email, presence: true
  validates :address_1, presence: true
  validates :postcode, presence: true

  def total_price

  	total = 0

  	order_products.each do |p|
  		total += p.price_in_pence
  	end

  	return total

  end

  def save_with_stripe

    if valid?

      @charge = Stripe::Charge.create(
        amount: total_price,
        currency: "gbp",
        card: stripe_card_token,
        description: email
        )

      save!
    end
  rescue
    errors.add :base, "Crap there was a problem with Stripe"
  end

end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  attr_accessible :order_id, :price_in_pence, :product_id, :quantity

  belongs_to :order
  belongs_to :product

  delegate :title, :description, :image, to: :product
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :previous_price_in_pence, :price_in_pence, :title, :image

  has_many :order_products
  has_many :orders, through: :order_products

  has_attached_file :image, styles: {
  	large: "500x500#",
  	medium: "300x300#",
  	thumb: "50x50#"
  }

	validates :title, presence: true
	validates :price_in_pence, presence: true, numericality: {
	greater_than: 0
	}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	helper_method :basket

  	def basket
  		if session[:basket].nil?
  			session[:basket] = Set.new
  		end

  		session[:basket]
  	end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
	
	# add somethings to the basket
	def create
		# find the product from our url
		@product = Product.find(params[:product_id])

		# then add it to our basket
		basket.add(@product.id)

		flash[:success] = "Added #{@product.title} to basket"

		redirect_to product_path(@product)

	end

	# remove from the basket
	def destroy
		# find the product from our url
		@product = Product.find(params[:product_id])

		# remove from basket
		basket.delete(@product.id)

		flash[:success] = "Removed #{@product.title} from your basket"

		redirect_to product_path(@product)

	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  	@order = Order.new
  	build_order_from_basket
  end

  def create
  	@order = Order.new(params[:order])
  	build_order_from_basket

  	if @order.save_with_stripe
  		basket.clear
  		flash[:success] = "High fives - We processed your order!"

      OrderMailer.admin(@order).deliver
      OrderMailer.customer(@order).deliver
  	else
  		render "new"
  	end
  end


def build_order_from_basket
	basket.each do |item|

  		@product = Product.find(item)

  		@order.order_products.build(
  			product_id: @product.id,
  			price_in_pence: @product.price_in_pence,
  			quantity: 1
  			)
  	end

end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def quid(num)

		number_to_currency (num / 100.0), unit: "&pound;"

	end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Escshop" %></title>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <meta name="stripe-key" content="<%= STRIPE_PUBLIC_KEY %>" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Escshop</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "About", "/about"  %></li>
              <li><%= link_to "FAQs", "/faqs"  %></li>
              <li><%= link_to "Basket (#{basket.size})", new_order_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
            <%= bootstrap_flash %>
            <%= yield %>
        </div><!--/row-->

      <footer>
        <p>&copy; Escape the City 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/orders/create.html.erb
<h1>Thanks so much....we took your cash and now its on us to deliver your goods!</h1>

	<p>Order: #<%= @order.id %></p>
	<p>Your name: <%= @order.name %></p>

app/views/orders/new.html.erb
<div class="span12">


	<table class="table table-striped">
	<tbody>
		<% @order.order_products.each do |item| %>
			<tr>
				<td><%= image_tag item.image(:thumb) %></td>
				
				<td><%= item.title %></td>

				<td><%= quid item.price_in_pence %></td>

				<td><%= link_to "Remove", product_basket_path(item.product), method: :delete %></td>
			</tr>
		<% end %>
	</tbody>

	<tfoot>
		<tr>
			<td colspan="2">Total price</rd>
			<td> <%= quid @order.total_price %></td>
			<td></td>
		</tr>
	</tfoot>

	</table>

<h2> Enter your payment details </h2>

	<%= simple_form_for @order do |f| %>

		<%= f.input :name %>
		<%= f.input :email %>
		<%= f.input :address_1 %>
		<%= f.input :address_2 %>
		<%= f.input :city %>
		<%= f.input :postcode %>

		<%= f.input :stripe_card_token, as: :hidden %>

		<div class="field">
			<label>Credit card number</label>
			<%= text_field_tag :card_number %>
		</div>

		<div class="field">
			<label>Security code</label>
			<%= text_field_tag :card_code %>
		</div>

		<div class="field">
			<label>Expiration date</label>
			<%= select_month nil, { add_month_numbers: true }, { name: nil, id: "card_month" } %>
			<%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { name: nil, id: "card_year" } %>
		</div>

		<%= f.button :submit, "Place order" %>

	<% end %>

</div>

app/views/products/index.html.erb
<% @products.each do |product| %>
	<div class="span4">

		<%= link_to product_path(product) do %>
			<%= image_tag product.image(:medium) %>
		<% end %>

		<h2><%= link_to product.title, product_path(product) %></h2>

		<p><%= quid product.price_in_pence %></p>
	
	</div>
	
<% end %>

app/views/products/show.html.erb
<div class="span6">
	<%= image_tag @product.image(:large) %>
</div>

<div class="span6">
	<h1><%= @product.title %></h1>

	<%= simple_format @product.description %>

	<div class="price">
		<% if @product.previous_price_in_pence %>
			Was <%= quid @product.previous_price_in_pence %>
		<% end %>

		<%= quid @product.price_in_pence %>
	</div>

	<p>
		<% if basket.include?(@product.id) %>

			<%= link_to product_basket_path(@product), method: :delete, class: "btn btn-danger btn-large" do %>
			<i class="icon icon-white icon-remove"></i> Remove from basket
			<% end %>

		<% else %>
			
			<%= link_to product_basket_path(@product), method: :post, class: "btn btn-primary btn-large" do %>
			<i class="icon icon-white icon-shopping-cart"></i> Buy
			
			<% end %>

		<% end %>
		
	</p>
</div>